# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
#dependency

pod 'SquarePointOfSaleSDK'
target 'EdenaCheckIn' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SquarePointOfSaleSDK'

  # Pods for EdenaCheckIn

  target 'EdenaCheckInTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EdenaCheckInUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
